language: minimal

before_deploy:
  - docker build -t monicaproject/observation-replayer:latest .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  - provider: script
    script: docker push monicaproject/observation-replayer:latest
    on:
      branch: master