version: '3.5'
services:
  observation-replayer:
    image: "janniswarnat/observation-replayer:latest"
    container_name: "observation-replayer"
    environment:
      BROKER_URI: "tcp://<monica_broker_address>:1883"
      BROKER_USERNAME: ""
      BROKER_PASSWORD: ""
      GOST_MQTT_PREFIX: GOST_PUETZ
      GOST_DB_HOST: "<monica_db_host>"
      GOST_DB_DATABASE: gost_puetz_2019
      GOST_DB_USER: "<username>"
      GOST_DB_PASSWORD: "<password>"
      DATASTREAM_IDS: "61,66"
      OBSERVATION_ID_START: 0
      OBSERVATION_ID_END: 2147483647
      OBSERVATION_INTERVAL_MS: 1000


